### ISSUE TITLE
1. Contracts / Actors development

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/spacetimeDAO#2]
- [x] #6 with access control for 2 types of moderators, citizen and government
- [x] Treasury/Escrow actor for storage deals
- [x] Function to create a proposal with a numeric identifier
- [x] 1 storage deal per proposal distributed evenly between 1. Proposal Evidence (x1), 2. Aditional local evidence (x2)
- [x] function to change the state per proposal
- [x] 6 proposal states (1. New proposal, 2. On review, 3. Solved, 4. Voting, 5. Rejected, 6. Funding)
- [x] Pin evidence CIDs on IPFS and link to the proposal id
- [x] Moderators voting (save the total number of votes per proposal, upvote, downvote, all moderators must vote)

**Comment by alessandromaci** [comment]
Based on yesterday's conversation, I am not sure we need an SBT for various participants (first point). We can have a role access model where the contract owner defines the permission per each address. 

This is my alternative proposed list of tasks for the MVP smart contract (actors) development:
- contract admin will select the address that will have some roles assigned
- deploy contract with funds
- function to create a proposal with a numeric identifier
- add some files to ipfs and link to the proposal
- function to change the state per proposal
- adding documents should also trigger a status change (for example move from review to finalised only after documents are sent)
- save the total number of votes per proposal (upvote and negative)

**Comment by alessandromaci** [comment]
Contract draft
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

import "@openzeppelin/contracts/access/AccessControl.sol";

contract SpaceTimeDAO is AccessControl {

    bytes32 internal constant MODERATOR = keccak256("MODERATOR");
    bytes32 internal constant CATALYST = keccak256("CATALYST");
    uint32 internal proposalId;

    struct Proposal {
        address owner;
        uint32 totalUpvote;
        uint32 totalDownvote;
        Status status;
    }

    enum Status {
        Review,
        Filtering,
        Filtering_Vote,
        Funding,
        Rejected,
        Solved
    }

    mapping(uint => Proposal) public proposalDetail;
    mapping (address => mapping (uint => bool)) proposalVoted; 

    error AlreadyVoted();
    error ProposalNotCreated();

    constructor() {  
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    function grantRoleModerator(address _address) external onlyRole(DEFAULT_ADMIN_ROLE) {
        _grantRole(MODERATOR, _address);
    }

    function grantRoleCatalyst(address _address) external onlyRole(DEFAULT_ADMIN_ROLE) {
        _grantRole(CATALYST, _address);
    }

    function create() external {

        Proposal memory proposal;
        proposal.owner = msg.sender;
        proposal.status = Status.Review;

        proposalDetail[proposalId] = proposal;

        proposalId += 1;        
    }

    function update(uint32 _proposalId, Status _status) public onlyRole(DEFAULT_ADMIN_ROLE) {
        proposalDetail[_proposalId].status = _status;
    }

    function upvote(uint32 _proposalId) public {

        if (proposalVoted[msg.sender][_proposalId]) {
            revert AlreadyVoted();
        }

        if (_proposalId >= proposalId) {
            revert ProposalNotCreated();
        }

        proposalDetail[_proposalId].totalUpvote += 1;

        proposalVoted[msg.sender][_proposalId] = true;
    }

    function downvote(uint32 _proposalId) public {

        if (proposalVoted[msg.sender][_proposalId]) {
            revert AlreadyVoted();
        }
        
        proposalDetail[_proposalId].totalDownvote += 1;

        proposalVoted[msg.sender][_proposalId] = true;
    }

}
```
