### ISSUE TITLE
2. Backend

### ISSUE THREAD

**Issue by HabacucMX** [zenbitETH/spacetimeDAO#3]
- [x] [Rainbow kit / wagmi set to hyperspace testnet](https://github.com/zenbitETH/spacetimeDAO/commit/446c7687e809c3db0ac4c74176c48b649a76bccf)
- [x] #5 
- [x] #17 
- [x] #18
- [x] Content pinning and fetching from IPFS
- [x] Fetching data from actors

**Comment by alessandromaci** [comment]
for IPFS, Infura has a very simple-to-use SDK. The only problem is that it requires an account on Infura and a credit card linked. It doesn't charge anything unless you pass a certain threshold, which is very unlikely we are going to pass during this hackathon

**Comment by HabacucMX** [comment]
We need to verify this part since storage helpers create the storage deal on filecoin for us and that is supposed to be managed by the governance or the escrow actor. I think is a 3-step process:

1. The actor (the governance or escrow contract) create the storage deal
2. The actor or a storage helper pin the CID to IPFS
3. The dapp fetches the CIDs pinned to IPFS
